id: ID9323903
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-29T16:11:48+00:00'
last_modified: '2022-06-07T18:27:43.447165+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG9480
  title: དགེ་ལུགས་པའི་དཔེ་ཐོ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessRestrictedByTbrc
  restrictedInChina: false
  base:
    D9B3:
      image_group_id: I1KG10503
      title: ''
      total_pages: 167
      order: 1
      base_file: D9B3.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
