id: P003218
initial_creation_type: ocr
created_at: 29/03/2020
last_modified_at: 2021-12-17 10:48:12.633048
source_metadata:
  id: bdr:W1KG9480
  title: དགེ་ལུགས་པའི་དཔེ་ཐོ།
  author: ''
  volumes:
    23e961662dec4aa1b0f47802fad3a633:
      image_group_id: I1KG10503
      title: ''
      volume_number: 1
      total_pages: 167
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessRestrictedByTbrc
  restrictedInChina: false
